# Generated by Django 5.0.2 on 2024-04-18 08:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.FileField(blank=True, null=True, upload_to='addclass/')),
                ('date', models.DateField()),
                ('Duration', models.IntegerField(blank=True, null=True)),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='syllabus/')),
                ('status', models.CharField(choices=[('running', 'Running'), ('off', 'Off')], default='Upcoming', max_length=20)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('attendance', models.CharField(blank=True, max_length=10, null=True)),
                ('my_class', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_track.myclass')),
            ],
        ),
        migrations.AddField(
            model_name='myclass',
            name='Teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_track.teacher'),
        ),
    ]
