# Generated by Django 5.0.2 on 2024-04-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
